<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        $data = array(
            array(
                'id' => 1,
                'title' => 'Договор',
                'sample_stage_id' => null,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 2,
                'title' => 'Замер на объекте',
                'sample_stage_id' => 1,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 3,
                'title' => 'Договор',
                'sample_stage_id' => 1,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 4,
                'title' => 'Предоплата',
                'sample_stage_id' => 1,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 5,
                'title' => 'Дизайн-проект',
                'sample_stage_id' => null,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 6,
                'title' => 'ТЗ на дизайн-проект',
                'sample_stage_id' => 5,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 7,
                'title' => 'Планировка',
                'sample_stage_id' => 5,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 8,
                'title' => 'Цветовой коллаж. Стилистика',
                'sample_stage_id' => 5,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 9,
                'title' => 'Технические чертежи помещения',
                'sample_stage_id' => 5,
                'sort' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 10,
                'title' => 'Предварительные чертежи мебели (корпусная, мягкая)',
                'sample_stage_id' => 5,
                'sort' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 11,
                'title' => 'Рендеры помещения',
                'sample_stage_id' => 5,
                'sort' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 12,
                'title' => 'Правки',
                'sample_stage_id' => 5,
                'sort' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 13,
                'title' => 'Готовый альбом',
                'sample_stage_id' => 5,
                'sort' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 14,
                'title' => 'Черновые работы',
                'sample_stage_id' => null,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 15,
                'title' => 'Выстраивание геометрии помещения',
                'sample_stage_id' => 14,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 16,
                'title' => 'Демонтаж-монтаж стен',
                'sample_stage_id' => 14,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 17,
                'title' => 'Замена труб отопления. Коллектор',
                'sample_stage_id' => 14,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 18,
                'title' => 'Черновое выравнивание стен',
                'sample_stage_id' => 14,
                'sort' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 19,
                'title' => 'Подрозетники, согласно дизайн-проекта',
                'sample_stage_id' => 14,
                'sort' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 20,
                'title' => 'Трасса кондиционерования, согласно дизай-проекта',
                'sample_stage_id' => 14,
                'sort' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 21,
                'title' => 'Электропроводка',
                'sample_stage_id' => 14,
                'sort' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 22,
                'title' => 'Формирование электро-щитка',
                'sample_stage_id' => 14,
                'sort' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 23,
                'title' => 'Формирование щитка слаботочных систем',
                'sample_stage_id' => 14,
                'sort' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 24,
                'title' => 'Установка радиаторов',
                'sample_stage_id' => 14,
                'sort' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 25,
                'title' => 'Установка подоконников',
                'sample_stage_id' => 14,
                'sort' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 26,
                'title' => 'Штукатурка, выравнивание стен',
                'sample_stage_id' => 14,
                'sort' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 27,
                'title' => 'Заливка стяжки',
                'sample_stage_id' => 14,
                'sort' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 28,
                'title' => 'Предчистовые работы',
                'sample_stage_id' => null,
                'sort' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 29,
                'title' => 'Установка ванны, душа',
                'sample_stage_id' => 28,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 30,
                'title' => 'Установка инсталляций',
                'sample_stage_id' => 28,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 31,
                'title' => 'Укладка плитки',
                'sample_stage_id' => 28,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 32,
                'title' => 'Формирование дверных проемов',
                'sample_stage_id' => 28,
                'sort' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 33,
                'title' => 'Замеры дверей',
                'sample_stage_id' => 28,
                'sort' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 34,
                'title' => 'Формирование каркаса потолка',
                'sample_stage_id' => 28,
                'sort' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 35,
                'title' => 'Электро проводка для осветительных приборов',
                'sample_stage_id' => 28,
                'sort' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 36,
                'title' => 'Формирование сантехнических гребенок с системой Нептун',
                'sample_stage_id' => 28,
                'sort' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 37,
                'title' => 'Выравнивание стен',
                'sample_stage_id' => 28,
                'sort' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 38,
                'title' => 'Шпаклевка, шкурение стен',
                'sample_stage_id' => 28,
                'sort' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 39,
                'title' => 'Полная подготовка к покраске',
                'sample_stage_id' => 28,
                'sort' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 40,
                'title' => 'Чистовые работы',
                'sample_stage_id' => null,
                'sort' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 41,
                'title' => 'Укладка напольного покрытия',
                'sample_stage_id' => 40,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 42,
                'title' => 'Покраска стен',
                'sample_stage_id' => 40,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 43,
                'title' => 'Установка дверей',
                'sample_stage_id' => 40,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 44,
                'title' => 'Установка осветительных приборов (потолок, стены)',
                'sample_stage_id' => 40,
                'sort' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 45,
                'title' => 'Установка розеток',
                'sample_stage_id' => 40,
                'sort' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 46,
                'title' => 'Финальные работы по чистовым',
                'sample_stage_id' => 40,
                'sort' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 47,
                'title' => 'Мебелировка',
                'sample_stage_id' => null,
                'sort' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 48,
                'title' => 'Установка корпусной мебели',
                'sample_stage_id' => 47,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 49,
                'title' => 'Установка мягкой мебели',
                'sample_stage_id' => 47,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 50,
                'title' => 'Бытовая Техника',
                'sample_stage_id' => null,
                'sort' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 51,
                'title' => 'Установка бытовой техники на кухню',
                'sample_stage_id' => 50,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 52,
                'title' => 'Установка бытовой техники в санузлы',
                'sample_stage_id' => 50,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 53,
                'title' => 'Установка ТВ',
                'sample_stage_id' => 50,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 54,
                'title' => 'Декорирование',
                'sample_stage_id' => null,
                'sort' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 55,
                'title' => 'Шторы',
                'sample_stage_id' => 54,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 56,
                'title' => 'Ковры',
                'sample_stage_id' => 54,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 57,
                'title' => 'Подушки, вазы',
                'sample_stage_id' => 54,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 58,
                'title' => 'Остальной декор',
                'sample_stage_id' => 54,
                'sort' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 59,
                'title' => 'Проверка квартиры',
                'sample_stage_id' => null,
                'sort' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 60,
                'title' => 'На соответствие рендерам',
                'sample_stage_id' => 59,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 61,
                'title' => 'Доработки',
                'sample_stage_id' => 59,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'id' => 62,
                'title' => 'Сдача',
                'sample_stage_id' => 59,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),



        );

        DB::table('sample_stages')->insert($data);




        // User::factory(10)->create();
        User::factory()->create([
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'role' => 'superadmin',
            'password' => Hash::make('11111111'),
        ]);

//        Project::factory(2)->create();
    }
}
