<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        $data = [
            // 1. Замер на объекте, формирование вкусов заказчика, формирование финального ТЗ для дизайнера
            [
                'id' => 1,
                'title' => 'Замер на объекте, формирование вкусов заказчика, формирование финального ТЗ для дизайнера',
                'sample_stage_id' => null,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'title' => 'Точный обмер помещения (стены, проёмы, перепады пола, расположение коммуникаций).',
                'sample_stage_id' => 1,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'title' => 'Сбор референсов и пожеланий заказчика (стиль, бюджет, сроки, ключевые зоны).',
                'sample_stage_id' => 1,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'title' => 'Составление технического задания для дизайнера: перечень комнат, розеток, освещения, техники.',
                'sample_stage_id' => 1,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 2. Дизайн-проект (тех. чертежи, визуализации, комплектации)
            [
                'id' => 5,
                'title' => 'Дизайн-проект (тех. чертежи, визуализации, комплектации)',
                'sample_stage_id' => null,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'title' => 'Разработка планов с расстановкой мебели, разводкой электрики, сантехники, вентиляции.',
                'sample_stage_id' => 5,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'title' => 'Фотореалистичные 3D-рендеры каждой комнаты (ракурсы «как будет вживую»).',
                'sample_stage_id' => 5,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'title' => 'Формирование таблицы комплектации: все материалы, мебель, свет, сантехника, декор с артикулами.',
                'sample_stage_id' => 5,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 3. Черновой ремонт (инженерные системы, сети, стены, потолок, санузел)
            [
                'id' => 9,
                'title' => 'Черновой ремонт (инженерные системы, сети, стены, потолок, санузел)',
                'sample_stage_id' => null,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'title' => 'Демонтаж до бетона (старая отделка, стяжка, перегородки) — сверка с планом перепланировки.',
                'sample_stage_id' => 9,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'title' => 'Монтаж новой электрики, слаботочки, водоснабжения, канализации, вентиляции (акт скрытых работ).',
                'sample_stage_id' => 9,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'title' => 'Выравнивание стен и потолка (штукатурка, стяжка пола, гидроизоляция в с/у) — контроль допусков по рендеру.',
                'sample_stage_id' => 9,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 4. Чистовой ремонт (плитка, напольное покрытие, светильники на потолке, диоды в стенах, покраска стен)
            [
                'id' => 13,
                'title' => 'Чистовой ремонт (плитка, напольное покрытие, светильники на потолке, диоды в стенах, покраска стен)',
                'sample_stage_id' => null,
                'sort' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'title' => 'Укладка плитки (с/у, кухня, прихожая) строго по схеме раскладки из дизайн-проекта.',
                'sample_stage_id' => 13,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'title' => 'Монтаж финишных покрытий пола (ламинат, паркет, кварцвинил) и потолочных светильников (точечные, треки, люстры).',
                'sample_stage_id' => 13,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'title' => 'Покраска стен и потолков в утверждённые цвета (пантоны, венцы) — проверка при разном освещении.',
                'sample_stage_id' => 13,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 5. Корпусная мебель (санузел, кухня, комнаты, коридор)
            [
                'id' => 17,
                'title' => 'Корпусная мебель (санузел, кухня, комнаты, коридор)',
                'sample_stage_id' => null,
                'sort' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'title' => 'Повторный обмер после чистовой отделки, сверка чертежей с реальными проёмами.',
                'sample_stage_id' => 17,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'title' => 'Изготовление / сборка кухни, шкафов-купе, систем хранения, тумб под раковину.',
                'sample_stage_id' => 17,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'title' => 'Установка с выверкой уровней и соответствием рендеру (цвет фасадов, фурнитура, встройка).',
                'sample_stage_id' => 17,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 6. Мягкая мебель (диваны, кровати, стулья)
            [
                'id' => 21,
                'title' => 'Мягкая мебель (диваны, кровати, стулья)',
                'sample_stage_id' => null,
                'sort' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'title' => 'Заказ по размерам из дизайн-проекта (диван в нишу, кровать с изголовьем нужной высоты).',
                'sample_stage_id' => 21,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'title' => 'Доставка и сборка, проверка механизмов (трансформация, подъёмные устройства).',
                'sample_stage_id' => 21,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'title' => 'Расстановка строго по плану (чтобы не закрывать розетки и светильники).',
                'sample_stage_id' => 21,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 7. Техника (крупная, мелкая бытовая техника, электроника)
            [
                'id' => 25,
                'title' => 'Техника (крупная, мелкая бытовая техника, электроника)',
                'sample_stage_id' => null,
                'sort' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'title' => 'Встраиваемая техника в кухню и санузлы (духовка, холодильник, стиральная машина) — монтаж в ниши.',
                'sample_stage_id' => 25,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'title' => 'Мелкая бытовая техника и электроника (ТВ, проектор, колонки, климатическое оборудование).',
                'sample_stage_id' => 25,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'title' => 'Подключение и тестирование, сверка с рендером (чтобы не торчали провода).',
                'sample_stage_id' => 25,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // 8. Декор (постельное, диффузоры, подушки, пледы, ковры, статуэтки, сухоцветы, вазы, картины и т.д.)
            [
                'id' => 29,
                'title' => 'Декор (постельное, диффузоры, подушки, пледы, ковры, статуэтки, сухоцветы, вазы, картины и т.д.)',
                'sample_stage_id' => null,
                'sort' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'title' => 'Текстиль: шторы, постельное бельё, покрывала, пледы, подушки — по подборке из рендеров.',
                'sample_stage_id' => 29,
                'sort' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'title' => 'Финальные акценты: ковры, вазы, сухоцветы, свечи, диффузоры, настенное искусство.',
                'sample_stage_id' => 29,
                'sort' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'title' => 'Расстановка декора по зонам и итоговая фотофиксация → сравнение «рендер vs реальность» для заказчика.',
                'sample_stage_id' => 29,
                'sort' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];




//        $data = array(
//            array(
//                'id' => 1,
//                'title' => 'Договор',
//                'sample_stage_id' => null,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 2,
//                'title' => 'Замер на объекте',
//                'sample_stage_id' => 1,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 3,
//                'title' => 'Договор',
//                'sample_stage_id' => 1,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 4,
//                'title' => 'Предоплата',
//                'sample_stage_id' => 1,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 5,
//                'title' => 'Дизайн-проект',
//                'sample_stage_id' => null,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 6,
//                'title' => 'ТЗ на дизайн-проект',
//                'sample_stage_id' => 5,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 7,
//                'title' => 'Планировка',
//                'sample_stage_id' => 5,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 8,
//                'title' => 'Цветовой коллаж. Стилистика',
//                'sample_stage_id' => 5,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 9,
//                'title' => 'Технические чертежи помещения',
//                'sample_stage_id' => 5,
//                'sort' => 4,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 10,
//                'title' => 'Предварительные чертежи мебели (корпусная, мягкая)',
//                'sample_stage_id' => 5,
//                'sort' => 5,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 11,
//                'title' => 'Рендеры помещения',
//                'sample_stage_id' => 5,
//                'sort' => 6,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 12,
//                'title' => 'Правки',
//                'sample_stage_id' => 5,
//                'sort' => 7,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 13,
//                'title' => 'Готовый альбом',
//                'sample_stage_id' => 5,
//                'sort' => 8,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 14,
//                'title' => 'Черновые работы',
//                'sample_stage_id' => null,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 15,
//                'title' => 'Выстраивание геометрии помещения',
//                'sample_stage_id' => 14,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 16,
//                'title' => 'Демонтаж-монтаж стен',
//                'sample_stage_id' => 14,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 17,
//                'title' => 'Замена труб отопления. Коллектор',
//                'sample_stage_id' => 14,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 18,
//                'title' => 'Черновое выравнивание стен',
//                'sample_stage_id' => 14,
//                'sort' => 4,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 19,
//                'title' => 'Подрозетники, согласно дизайн-проекта',
//                'sample_stage_id' => 14,
//                'sort' => 5,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 20,
//                'title' => 'Трасса кондиционерования, согласно дизай-проекта',
//                'sample_stage_id' => 14,
//                'sort' => 6,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 21,
//                'title' => 'Электропроводка',
//                'sample_stage_id' => 14,
//                'sort' => 7,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 22,
//                'title' => 'Формирование электро-щитка',
//                'sample_stage_id' => 14,
//                'sort' => 8,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 23,
//                'title' => 'Формирование щитка слаботочных систем',
//                'sample_stage_id' => 14,
//                'sort' => 9,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 24,
//                'title' => 'Установка радиаторов',
//                'sample_stage_id' => 14,
//                'sort' => 10,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 25,
//                'title' => 'Установка подоконников',
//                'sample_stage_id' => 14,
//                'sort' => 11,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 26,
//                'title' => 'Штукатурка, выравнивание стен',
//                'sample_stage_id' => 14,
//                'sort' => 12,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 27,
//                'title' => 'Заливка стяжки',
//                'sample_stage_id' => 14,
//                'sort' => 13,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 28,
//                'title' => 'Предчистовые работы',
//                'sample_stage_id' => null,
//                'sort' => 4,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 29,
//                'title' => 'Установка ванны, душа',
//                'sample_stage_id' => 28,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 30,
//                'title' => 'Установка инсталляций',
//                'sample_stage_id' => 28,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 31,
//                'title' => 'Укладка плитки',
//                'sample_stage_id' => 28,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 32,
//                'title' => 'Формирование дверных проемов',
//                'sample_stage_id' => 28,
//                'sort' => 5,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 33,
//                'title' => 'Замеры дверей',
//                'sample_stage_id' => 28,
//                'sort' => 6,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 34,
//                'title' => 'Формирование каркаса потолка',
//                'sample_stage_id' => 28,
//                'sort' => 7,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 35,
//                'title' => 'Электро проводка для осветительных приборов',
//                'sample_stage_id' => 28,
//                'sort' => 8,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 36,
//                'title' => 'Формирование сантехнических гребенок с системой Нептун',
//                'sample_stage_id' => 28,
//                'sort' => 9,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 37,
//                'title' => 'Выравнивание стен',
//                'sample_stage_id' => 28,
//                'sort' => 10,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 38,
//                'title' => 'Шпаклевка, шкурение стен',
//                'sample_stage_id' => 28,
//                'sort' => 11,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 39,
//                'title' => 'Полная подготовка к покраске',
//                'sample_stage_id' => 28,
//                'sort' => 12,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 40,
//                'title' => 'Чистовые работы',
//                'sample_stage_id' => null,
//                'sort' => 5,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 41,
//                'title' => 'Укладка напольного покрытия',
//                'sample_stage_id' => 40,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 42,
//                'title' => 'Покраска стен',
//                'sample_stage_id' => 40,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 43,
//                'title' => 'Установка дверей',
//                'sample_stage_id' => 40,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 44,
//                'title' => 'Установка осветительных приборов (потолок, стены)',
//                'sample_stage_id' => 40,
//                'sort' => 4,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 45,
//                'title' => 'Установка розеток',
//                'sample_stage_id' => 40,
//                'sort' => 5,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 46,
//                'title' => 'Финальные работы по чистовым',
//                'sample_stage_id' => 40,
//                'sort' => 6,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 47,
//                'title' => 'Мебелировка',
//                'sample_stage_id' => null,
//                'sort' => 6,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 48,
//                'title' => 'Установка корпусной мебели',
//                'sample_stage_id' => 47,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 49,
//                'title' => 'Установка мягкой мебели',
//                'sample_stage_id' => 47,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 50,
//                'title' => 'Бытовая Техника',
//                'sample_stage_id' => null,
//                'sort' => 7,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 51,
//                'title' => 'Установка бытовой техники на кухню',
//                'sample_stage_id' => 50,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 52,
//                'title' => 'Установка бытовой техники в санузлы',
//                'sample_stage_id' => 50,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 53,
//                'title' => 'Установка ТВ',
//                'sample_stage_id' => 50,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 54,
//                'title' => 'Декорирование',
//                'sample_stage_id' => null,
//                'sort' => 8,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 55,
//                'title' => 'Шторы',
//                'sample_stage_id' => 54,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 56,
//                'title' => 'Ковры',
//                'sample_stage_id' => 54,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 57,
//                'title' => 'Подушки, вазы',
//                'sample_stage_id' => 54,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 58,
//                'title' => 'Остальной декор',
//                'sample_stage_id' => 54,
//                'sort' => 4,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 59,
//                'title' => 'Проверка квартиры',
//                'sample_stage_id' => null,
//                'sort' => 9,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 60,
//                'title' => 'На соответствие рендерам',
//                'sample_stage_id' => 59,
//                'sort' => 1,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 61,
//                'title' => 'Доработки',
//                'sample_stage_id' => 59,
//                'sort' => 2,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//            array(
//                'id' => 62,
//                'title' => 'Сдача',
//                'sample_stage_id' => 59,
//                'sort' => 3,
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now(),
//            ),
//
//
//
//        );

        DB::table('sample_stages')->insert($data);




        // User::factory(10)->create();
        User::factory()->create([
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'role' => 'superadmin',
            'password' => Hash::make('11111111'),
        ]);

//        Project::factory(2)->create();
    }
}
